Neos:
  Neos:
    eventLog:
      enabled: true
    modules:
      management:
        submodules:
          history:
            controller: \AE\History\Controller\HistoryController
            privilegeTarget: 'AE.History:BackendModule'
            additionalResources:
              styleSheets:
                'AE.History': 'resource://AE.History/Public/Styles/Module.css'
              javaScripts:
                'AE.History': 'resource://AE.History/Public/JavaScript/App.js'

  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'AE.History:Controllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'AE\History\Controller\.*'
